version: "3.9"
services:
  rw-build-env:
    image: public.ecr.aws/x5u3w5h6/rw-build-env:latest
#    build:
#      context: ..
#      dockerfile: ./ci/Dockerfile
#      target: risingwave-build-env
    volumes:
      - ..:/risingwave


